name: Android Release Workflow2

# Launches when create PR to the develop branch
on:
  pull_request:
    branches: [ develop ]
#  pull_request:
#    branches:
#      - master
#    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    if: contains(join(github.event.pull_request.labels.*.name), 'Release')
#    if: github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v2
      - name: hoge
        run: |
          echo '${{ toJSON(github) }}'

#      - name:
#        id: commit-hash
#        run: |
#          echo "::set-output name=sha-short::$(git rev-parse --short HEAD)"
#      - name: Set APP_VERSION
#        id: app-version
#        run: |
#          VERSION=$(grep -Eo 'versionName ".*"' ./app/build.gradle | grep -Eo '[0-9]+.[0-9]+')
#          echo "::set-output name=version::$VERSION"
#      - name: Build with Gradle
#        run: echo ${{ steps.app-version.outputs.version }}
#      - name: post messaage to slack
#        uses: tokorom/action-slack-incoming-webhook@main
#        env:
#          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#        with:
#          text: ":clap: New app was deployed!! :clap: ${{ steps.app-version.outputs.version }} - ${{ steps.commit-hash.outputs.sha-short }}"
#        attachments: |
#          [
#            {
#              "color": "good",
#              "author_name": "${{ github.actor }}",
#              "author_icon": "${{ github.event.sender.avatar_url }}",
#              "fields": [
#                {
#                  "title": "Commit Message",
#                  "value": "${{ env.commit_message }}"
#                },
#                {
#                  "title": "GitHub Actions URL",
#                  "value": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
#                },
#                {
#                  "title": "Compare URL",
#                  "value": "${{ github.event.compare }}"
#                }
#              ]
#            }
#          ]