name: Android Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: echo ${{ github.event.inputs.version }} | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+'

      - uses: actions/checkout@v2

      - name: VERSION
        id: version
        run: |
          sed -ir -e 's/versionName "[0-9]+\.[0-9]+\.[0-9]+"/versionName "${{ github.event.inputs.version }}"/g' app/build.gradle
          NAME=$(grep -Eo 'versionName ".*"' ./app/build.gradle | grep -Eo '[0-9]+.[0-9]+.[0-9]+')
          echo "::set-output name=name::$NAME"

      - name: Hogeeeee
        run: echo ${{ steps.version.outputs.name }}

      - name: branch
        run: |
          git checkout -b release_${{ steps.version.outputs.name }}
          git push origin release_${{ steps.version.outputs.name }}