name: Android Release Workflow

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set APP_VERSION
      id: app_version
      run: |
        VERSION=$(grep -Eo 'versionName ".*"' ./app/build.gradle | grep -Eo '[0-9]+.[0-9]+.[0-9]+')
        echo "::set-output name=version::$VERSION"
      - name: Build with Gradle
        run: echo ${{ steps.app_version.outputs.version }}
      - name: post messaage to slack
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: ":clap: New app was deployed!! :clap: ${{ steps.app_version.outputs.version }}"
#        attachments: |
#          [
#            {
#              "color": "good",
#              "author_name": "${{ github.actor }}",
#              "author_icon": "${{ github.event.sender.avatar_url }}",
#              "fields": [
#                {
#                  "title": "Commit Message",
#                  "value": "${{ env.commit_message }}"
#                },
#                {
#                  "title": "GitHub Actions URL",
#                  "value": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
#                },
#                {
#                  "title": "Compare URL",
#                  "value": "${{ github.event.compare }}"
#                }
#              ]
#            }
#          ]