name: Android Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: VERSION
        id: version
        run: |
          sed -i -e 's/versionName "[0-9]*\.[0-9]*\.[0-9]*"/versionName "${{ github.event.inputs.version }}"/g' app/build.gradle > app/build.gradle
          NAME=$(grep -Eo 'versionName ".*"' ./app/build.gradle | grep -Eo '[0-9]+.[0-9]+.[0-9]+')
          echo "::set-output name=name::$NAME"

      - name: Hogeeeee
        run: echo ${{ steps.version.outputs.name }}
