name: Android Release Workflow2

# Launches when create PR to the develop branch
on:
  pull_request:
    branches:
      - develop

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'

      - name: cache bundle
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: setup bundle
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run detekt
        run: ./gradlew detekt

      - name: Run ktlin
        run: ./gradlew ktlint

      - name: Run Danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bundle exec danger

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name:
        id: commit-hash
        run: |
          echo "::set-output name=sha-short::$(git rev-parse --short HEAD)"
      - name: Set APP_VERSION
        id: app-version
        run: |
          VERSION=$(grep -Eo 'versionName ".*"' ./app/build.gradle | grep -Eo '[0-9]+.[0-9]+')
          echo "::set-output name=version::$VERSION"
      - name: Build with Gradle
        run: echo ${{ steps.app-version.outputs.version }}
      - name: post messaage to slack
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: ":clap: New app was deployed!! :clap: ${{ steps.app-version.outputs.version }} - ${{ steps.commit-hash.outputs.sha-short }}"
#        attachments: |
#          [
#            {
#              "color": "good",
#              "author_name": "${{ github.actor }}",
#              "author_icon": "${{ github.event.sender.avatar_url }}",
#              "fields": [
#                {
#                  "title": "Commit Message",
#                  "value": "${{ env.commit_message }}"
#                },
#                {
#                  "title": "GitHub Actions URL",
#                  "value": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
#                },
#                {
#                  "title": "Compare URL",
#                  "value": "${{ github.event.compare }}"
#                }
#              ]
#            }
#          ]